//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3MServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.LigneCommande = new HashSet<LigneCommande>();
        }
    
        public int id_commande { get; set; }
        public Nullable<System.DateTime> date_arrive { get; set; }
        public Nullable<System.DateTime> date_souhaite { get; set; }
        public Nullable<bool> confirme { get; set; }
        public Nullable<System.DateTime> date_commande { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneCommande> LigneCommande { get; set; }
    }
}
