//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3MServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public int id_ligneCommande { get; set; }
        public Nullable<int> id_produit { get; set; }
        public Nullable<int> id_commande { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<decimal> prix_grossiste { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
