//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3MServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Vente = new HashSet<Vente>();
            this.LigneCommande = new HashSet<LigneCommande>();
        }
    
        public int id_produit { get; set; }
        public Nullable<int> id_fournisseur { get; set; }
        public string nom { get; set; }
        public string image { get; set; }
        public Nullable<decimal> prix_vente { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<System.DateTime> date_expiration { get; set; }
        public Nullable<System.DateTime> date_ajout { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vente> Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneCommande> LigneCommande { get; set; }
    }
}
