//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3MServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public int id_vente { get; set; }
        public Nullable<int> id_produit { get; set; }
        public Nullable<int> quantite_vendu { get; set; }
        public Nullable<System.DateTime> date_ajout { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
