//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3M.CommandeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Commande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> confirmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_arriveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_souhaiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_commandeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> confirme {
            get {
                return this.confirmeField;
            }
            set {
                if ((this.confirmeField.Equals(value) != true)) {
                    this.confirmeField = value;
                    this.RaisePropertyChanged("confirme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_arrive {
            get {
                return this.date_arriveField;
            }
            set {
                if ((this.date_arriveField.Equals(value) != true)) {
                    this.date_arriveField = value;
                    this.RaisePropertyChanged("date_arrive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_commande {
            get {
                return this.date_commandeField;
            }
            set {
                if ((this.date_commandeField.Equals(value) != true)) {
                    this.date_commandeField = value;
                    this.RaisePropertyChanged("date_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_souhaite {
            get {
                return this.date_souhaiteField;
            }
            set {
                if ((this.date_souhaiteField.Equals(value) != true)) {
                    this.date_souhaiteField = value;
                    this.RaisePropertyChanged("date_souhaite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LigneCommande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class LigneCommande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.Commande CommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ligneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_grossisteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.Commande Commande {
            get {
                return this.CommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandeField, value) != true)) {
                    this.CommandeField = value;
                    this.RaisePropertyChanged("Commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_ligneCommande {
            get {
                return this.id_ligneCommandeField;
            }
            set {
                if ((this.id_ligneCommandeField.Equals(value) != true)) {
                    this.id_ligneCommandeField = value;
                    this.RaisePropertyChanged("id_ligneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_grossiste {
            get {
                return this.prix_grossisteField;
            }
            set {
                if ((this.prix_grossisteField.Equals(value) != true)) {
                    this.prix_grossisteField = value;
                    this.RaisePropertyChanged("prix_grossiste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produit", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Produit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.Fournisseur FournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.Vente[] VenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_expirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.Fournisseur Fournisseur {
            get {
                return this.FournisseurField;
            }
            set {
                if ((object.ReferenceEquals(this.FournisseurField, value) != true)) {
                    this.FournisseurField = value;
                    this.RaisePropertyChanged("Fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.Vente[] Vente {
            get {
                return this.VenteField;
            }
            set {
                if ((object.ReferenceEquals(this.VenteField, value) != true)) {
                    this.VenteField = value;
                    this.RaisePropertyChanged("Vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_expiration {
            get {
                return this.date_expirationField;
            }
            set {
                if ((this.date_expirationField.Equals(value) != true)) {
                    this.date_expirationField = value;
                    this.RaisePropertyChanged("date_expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_vente {
            get {
                return this.prix_venteField;
            }
            set {
                if ((this.prix_venteField.Equals(value) != true)) {
                    this.prix_venteField = value;
                    this.RaisePropertyChanged("prix_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fournisseur", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Fournisseur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.Produit[] ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.Produit[] Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseField, value) != true)) {
                    this.adresseField = value;
                    this.RaisePropertyChanged("adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vente", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Vente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.CommandeService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantite_venduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.CommandeService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_vente {
            get {
                return this.id_venteField;
            }
            set {
                if ((this.id_venteField.Equals(value) != true)) {
                    this.id_venteField = value;
                    this.RaisePropertyChanged("id_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite_vendu {
            get {
                return this.quantite_venduField;
            }
            set {
                if ((this.quantite_venduField.Equals(value) != true)) {
                    this.quantite_venduField = value;
                    this.RaisePropertyChanged("quantite_vendu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProduitCommande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class ProduitCommande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prix_grossisteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_produit {
            get {
                return this.Id_produitField;
            }
            set {
                if ((this.Id_produitField.Equals(value) != true)) {
                    this.Id_produitField = value;
                    this.RaisePropertyChanged("Id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prix_grossiste {
            get {
                return this.Prix_grossisteField;
            }
            set {
                if ((this.Prix_grossisteField.Equals(value) != true)) {
                    this.Prix_grossisteField = value;
                    this.RaisePropertyChanged("Prix_grossiste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommandeService.ICommandeServiceWCF")]
    public interface ICommandeServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/add", ReplyAction="http://tempuri.org/ICommandeServiceWCF/addResponse")]
        int add(GestionDeStockI3M.CommandeService.Commande commande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/add", ReplyAction="http://tempuri.org/ICommandeServiceWCF/addResponse")]
        System.Threading.Tasks.Task<int> addAsync(GestionDeStockI3M.CommandeService.Commande commande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/commandeEnCours", ReplyAction="http://tempuri.org/ICommandeServiceWCF/commandeEnCoursResponse")]
        GestionDeStockI3M.CommandeService.Commande[] commandeEnCours();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/commandeEnCours", ReplyAction="http://tempuri.org/ICommandeServiceWCF/commandeEnCoursResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.Commande[]> commandeEnCoursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/commandeEnRetard", ReplyAction="http://tempuri.org/ICommandeServiceWCF/commandeEnRetardResponse")]
        GestionDeStockI3M.CommandeService.Commande[] commandeEnRetard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/commandeEnRetard", ReplyAction="http://tempuri.org/ICommandeServiceWCF/commandeEnRetardResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.Commande[]> commandeEnRetardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/commandeConfirme", ReplyAction="http://tempuri.org/ICommandeServiceWCF/commandeConfirmeResponse")]
        GestionDeStockI3M.CommandeService.Commande[] commandeConfirme();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/commandeConfirme", ReplyAction="http://tempuri.org/ICommandeServiceWCF/commandeConfirmeResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.Commande[]> commandeConfirmeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/prixCommande", ReplyAction="http://tempuri.org/ICommandeServiceWCF/prixCommandeResponse")]
        decimal prixCommande(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/prixCommande", ReplyAction="http://tempuri.org/ICommandeServiceWCF/prixCommandeResponse")]
        System.Threading.Tasks.Task<decimal> prixCommandeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/confirmeCommande", ReplyAction="http://tempuri.org/ICommandeServiceWCF/confirmeCommandeResponse")]
        int confirmeCommande(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/confirmeCommande", ReplyAction="http://tempuri.org/ICommandeServiceWCF/confirmeCommandeResponse")]
        System.Threading.Tasks.Task<int> confirmeCommandeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/delete", ReplyAction="http://tempuri.org/ICommandeServiceWCF/deleteResponse")]
        int delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/delete", ReplyAction="http://tempuri.org/ICommandeServiceWCF/deleteResponse")]
        System.Threading.Tasks.Task<int> deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/GetProduitsOfCommande", ReplyAction="http://tempuri.org/ICommandeServiceWCF/GetProduitsOfCommandeResponse")]
        GestionDeStockI3M.CommandeService.ProduitCommande[] GetProduitsOfCommande(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandeServiceWCF/GetProduitsOfCommande", ReplyAction="http://tempuri.org/ICommandeServiceWCF/GetProduitsOfCommandeResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.ProduitCommande[]> GetProduitsOfCommandeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommandeServiceWCFChannel : GestionDeStockI3M.CommandeService.ICommandeServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandeServiceWCFClient : System.ServiceModel.ClientBase<GestionDeStockI3M.CommandeService.ICommandeServiceWCF>, GestionDeStockI3M.CommandeService.ICommandeServiceWCF {
        
        public CommandeServiceWCFClient() {
        }
        
        public CommandeServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandeServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandeServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandeServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add(GestionDeStockI3M.CommandeService.Commande commande) {
            return base.Channel.add(commande);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(GestionDeStockI3M.CommandeService.Commande commande) {
            return base.Channel.addAsync(commande);
        }
        
        public GestionDeStockI3M.CommandeService.Commande[] commandeEnCours() {
            return base.Channel.commandeEnCours();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.Commande[]> commandeEnCoursAsync() {
            return base.Channel.commandeEnCoursAsync();
        }
        
        public GestionDeStockI3M.CommandeService.Commande[] commandeEnRetard() {
            return base.Channel.commandeEnRetard();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.Commande[]> commandeEnRetardAsync() {
            return base.Channel.commandeEnRetardAsync();
        }
        
        public GestionDeStockI3M.CommandeService.Commande[] commandeConfirme() {
            return base.Channel.commandeConfirme();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.Commande[]> commandeConfirmeAsync() {
            return base.Channel.commandeConfirmeAsync();
        }
        
        public decimal prixCommande(int id) {
            return base.Channel.prixCommande(id);
        }
        
        public System.Threading.Tasks.Task<decimal> prixCommandeAsync(int id) {
            return base.Channel.prixCommandeAsync(id);
        }
        
        public int confirmeCommande(int id) {
            return base.Channel.confirmeCommande(id);
        }
        
        public System.Threading.Tasks.Task<int> confirmeCommandeAsync(int id) {
            return base.Channel.confirmeCommandeAsync(id);
        }
        
        public int delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        public GestionDeStockI3M.CommandeService.ProduitCommande[] GetProduitsOfCommande(int id) {
            return base.Channel.GetProduitsOfCommande(id);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.CommandeService.ProduitCommande[]> GetProduitsOfCommandeAsync(int id) {
            return base.Channel.GetProduitsOfCommandeAsync(id);
        }
    }
}
