//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3M.ProduitService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produit", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Produit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.Fournisseur FournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.Vente[] VenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_expirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.Fournisseur Fournisseur {
            get {
                return this.FournisseurField;
            }
            set {
                if ((object.ReferenceEquals(this.FournisseurField, value) != true)) {
                    this.FournisseurField = value;
                    this.RaisePropertyChanged("Fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.Vente[] Vente {
            get {
                return this.VenteField;
            }
            set {
                if ((object.ReferenceEquals(this.VenteField, value) != true)) {
                    this.VenteField = value;
                    this.RaisePropertyChanged("Vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_expiration {
            get {
                return this.date_expirationField;
            }
            set {
                if ((this.date_expirationField.Equals(value) != true)) {
                    this.date_expirationField = value;
                    this.RaisePropertyChanged("date_expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_vente {
            get {
                return this.prix_venteField;
            }
            set {
                if ((this.prix_venteField.Equals(value) != true)) {
                    this.prix_venteField = value;
                    this.RaisePropertyChanged("prix_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fournisseur", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Fournisseur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.Produit[] ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.Produit[] Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseField, value) != true)) {
                    this.adresseField = value;
                    this.RaisePropertyChanged("adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LigneCommande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class LigneCommande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.Commande CommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ligneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_grossisteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.Commande Commande {
            get {
                return this.CommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandeField, value) != true)) {
                    this.CommandeField = value;
                    this.RaisePropertyChanged("Commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_ligneCommande {
            get {
                return this.id_ligneCommandeField;
            }
            set {
                if ((this.id_ligneCommandeField.Equals(value) != true)) {
                    this.id_ligneCommandeField = value;
                    this.RaisePropertyChanged("id_ligneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_grossiste {
            get {
                return this.prix_grossisteField;
            }
            set {
                if ((this.prix_grossisteField.Equals(value) != true)) {
                    this.prix_grossisteField = value;
                    this.RaisePropertyChanged("prix_grossiste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vente", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Vente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantite_venduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_vente {
            get {
                return this.id_venteField;
            }
            set {
                if ((this.id_venteField.Equals(value) != true)) {
                    this.id_venteField = value;
                    this.RaisePropertyChanged("id_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite_vendu {
            get {
                return this.quantite_venduField;
            }
            set {
                if ((this.quantite_venduField.Equals(value) != true)) {
                    this.quantite_venduField = value;
                    this.RaisePropertyChanged("quantite_vendu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Commande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.ProduitService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> confirmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_arriveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_souhaiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_commandeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.ProduitService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> confirme {
            get {
                return this.confirmeField;
            }
            set {
                if ((this.confirmeField.Equals(value) != true)) {
                    this.confirmeField = value;
                    this.RaisePropertyChanged("confirme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_arrive {
            get {
                return this.date_arriveField;
            }
            set {
                if ((this.date_arriveField.Equals(value) != true)) {
                    this.date_arriveField = value;
                    this.RaisePropertyChanged("date_arrive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_commande {
            get {
                return this.date_commandeField;
            }
            set {
                if ((this.date_commandeField.Equals(value) != true)) {
                    this.date_commandeField = value;
                    this.RaisePropertyChanged("date_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_souhaite {
            get {
                return this.date_souhaiteField;
            }
            set {
                if ((this.date_souhaiteField.Equals(value) != true)) {
                    this.date_souhaiteField = value;
                    this.RaisePropertyChanged("date_souhaite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProduitService.IProduitServiceWCF")]
    public interface IProduitServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findAll", ReplyAction="http://tempuri.org/IProduitServiceWCF/findAllResponse")]
        GestionDeStockI3M.ProduitService.Produit[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findAll", ReplyAction="http://tempuri.org/IProduitServiceWCF/findAllResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/find", ReplyAction="http://tempuri.org/IProduitServiceWCF/findResponse")]
        GestionDeStockI3M.ProduitService.Produit find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/find", ReplyAction="http://tempuri.org/IProduitServiceWCF/findResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit> findAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/add", ReplyAction="http://tempuri.org/IProduitServiceWCF/addResponse")]
        void add(GestionDeStockI3M.ProduitService.Produit p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/add", ReplyAction="http://tempuri.org/IProduitServiceWCF/addResponse")]
        System.Threading.Tasks.Task addAsync(GestionDeStockI3M.ProduitService.Produit p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findByFournisseur", ReplyAction="http://tempuri.org/IProduitServiceWCF/findByFournisseurResponse")]
        GestionDeStockI3M.ProduitService.Produit[] findByFournisseur(int id_fourn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findByFournisseur", ReplyAction="http://tempuri.org/IProduitServiceWCF/findByFournisseurResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findByFournisseurAsync(int id_fourn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/updateQuantite", ReplyAction="http://tempuri.org/IProduitServiceWCF/updateQuantiteResponse")]
        int updateQuantite(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/updateQuantite", ReplyAction="http://tempuri.org/IProduitServiceWCF/updateQuantiteResponse")]
        System.Threading.Tasks.Task<int> updateQuantiteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findAllFournisseur", ReplyAction="http://tempuri.org/IProduitServiceWCF/findAllFournisseurResponse")]
        GestionDeStockI3M.ProduitService.Fournisseur[] findAllFournisseur();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findAllFournisseur", ReplyAction="http://tempuri.org/IProduitServiceWCF/findAllFournisseurResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Fournisseur[]> findAllFournisseurAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findFournisseurByName", ReplyAction="http://tempuri.org/IProduitServiceWCF/findFournisseurByNameResponse")]
        GestionDeStockI3M.ProduitService.Fournisseur findFournisseurByName(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findFournisseurByName", ReplyAction="http://tempuri.org/IProduitServiceWCF/findFournisseurByNameResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Fournisseur> findFournisseurByNameAsync(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findProductsByName", ReplyAction="http://tempuri.org/IProduitServiceWCF/findProductsByNameResponse")]
        GestionDeStockI3M.ProduitService.Produit[] findProductsByName(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findProductsByName", ReplyAction="http://tempuri.org/IProduitServiceWCF/findProductsByNameResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findProductsByNameAsync(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findAvaibleProducts", ReplyAction="http://tempuri.org/IProduitServiceWCF/findAvaibleProductsResponse")]
        GestionDeStockI3M.ProduitService.Produit[] findAvaibleProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findAvaibleProducts", ReplyAction="http://tempuri.org/IProduitServiceWCF/findAvaibleProductsResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findAvaibleProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findProductsNotAvaible", ReplyAction="http://tempuri.org/IProduitServiceWCF/findProductsNotAvaibleResponse")]
        GestionDeStockI3M.ProduitService.Produit[] findProductsNotAvaible();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findProductsNotAvaible", ReplyAction="http://tempuri.org/IProduitServiceWCF/findProductsNotAvaibleResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findProductsNotAvaibleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findDestockedProduts", ReplyAction="http://tempuri.org/IProduitServiceWCF/findDestockedProdutsResponse")]
        GestionDeStockI3M.ProduitService.Produit[] findDestockedProduts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findDestockedProduts", ReplyAction="http://tempuri.org/IProduitServiceWCF/findDestockedProdutsResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findDestockedProdutsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/delete", ReplyAction="http://tempuri.org/IProduitServiceWCF/deleteResponse")]
        void delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/delete", ReplyAction="http://tempuri.org/IProduitServiceWCF/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findProductsById", ReplyAction="http://tempuri.org/IProduitServiceWCF/findProductsByIdResponse")]
        GestionDeStockI3M.ProduitService.Fournisseur findProductsById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/findProductsById", ReplyAction="http://tempuri.org/IProduitServiceWCF/findProductsByIdResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Fournisseur> findProductsByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/edit", ReplyAction="http://tempuri.org/IProduitServiceWCF/editResponse")]
        void edit(GestionDeStockI3M.ProduitService.Produit p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduitServiceWCF/edit", ReplyAction="http://tempuri.org/IProduitServiceWCF/editResponse")]
        System.Threading.Tasks.Task editAsync(GestionDeStockI3M.ProduitService.Produit p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProduitServiceWCFChannel : GestionDeStockI3M.ProduitService.IProduitServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProduitServiceWCFClient : System.ServiceModel.ClientBase<GestionDeStockI3M.ProduitService.IProduitServiceWCF>, GestionDeStockI3M.ProduitService.IProduitServiceWCF {
        
        public ProduitServiceWCFClient() {
        }
        
        public ProduitServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProduitServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProduitServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProduitServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionDeStockI3M.ProduitService.Produit[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public GestionDeStockI3M.ProduitService.Produit find(int id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit> findAsync(int id) {
            return base.Channel.findAsync(id);
        }
        
        public void add(GestionDeStockI3M.ProduitService.Produit p) {
            base.Channel.add(p);
        }
        
        public System.Threading.Tasks.Task addAsync(GestionDeStockI3M.ProduitService.Produit p) {
            return base.Channel.addAsync(p);
        }
        
        public GestionDeStockI3M.ProduitService.Produit[] findByFournisseur(int id_fourn) {
            return base.Channel.findByFournisseur(id_fourn);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findByFournisseurAsync(int id_fourn) {
            return base.Channel.findByFournisseurAsync(id_fourn);
        }
        
        public int updateQuantite(int id) {
            return base.Channel.updateQuantite(id);
        }
        
        public System.Threading.Tasks.Task<int> updateQuantiteAsync(int id) {
            return base.Channel.updateQuantiteAsync(id);
        }
        
        public GestionDeStockI3M.ProduitService.Fournisseur[] findAllFournisseur() {
            return base.Channel.findAllFournisseur();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Fournisseur[]> findAllFournisseurAsync() {
            return base.Channel.findAllFournisseurAsync();
        }
        
        public GestionDeStockI3M.ProduitService.Fournisseur findFournisseurByName(string nom) {
            return base.Channel.findFournisseurByName(nom);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Fournisseur> findFournisseurByNameAsync(string nom) {
            return base.Channel.findFournisseurByNameAsync(nom);
        }
        
        public GestionDeStockI3M.ProduitService.Produit[] findProductsByName(string nom) {
            return base.Channel.findProductsByName(nom);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findProductsByNameAsync(string nom) {
            return base.Channel.findProductsByNameAsync(nom);
        }
        
        public GestionDeStockI3M.ProduitService.Produit[] findAvaibleProducts() {
            return base.Channel.findAvaibleProducts();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findAvaibleProductsAsync() {
            return base.Channel.findAvaibleProductsAsync();
        }
        
        public GestionDeStockI3M.ProduitService.Produit[] findProductsNotAvaible() {
            return base.Channel.findProductsNotAvaible();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findProductsNotAvaibleAsync() {
            return base.Channel.findProductsNotAvaibleAsync();
        }
        
        public GestionDeStockI3M.ProduitService.Produit[] findDestockedProduts() {
            return base.Channel.findDestockedProduts();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Produit[]> findDestockedProdutsAsync() {
            return base.Channel.findDestockedProdutsAsync();
        }
        
        public void delete(int id) {
            base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        public GestionDeStockI3M.ProduitService.Fournisseur findProductsById(int id) {
            return base.Channel.findProductsById(id);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.ProduitService.Fournisseur> findProductsByIdAsync(int id) {
            return base.Channel.findProductsByIdAsync(id);
        }
        
        public void edit(GestionDeStockI3M.ProduitService.Produit p) {
            base.Channel.edit(p);
        }
        
        public System.Threading.Tasks.Task editAsync(GestionDeStockI3M.ProduitService.Produit p) {
            return base.Channel.editAsync(p);
        }
    }
}
