//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3M.FournisseurService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fournisseur", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Fournisseur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.Produit[] ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.Produit[] Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseField, value) != true)) {
                    this.adresseField = value;
                    this.RaisePropertyChanged("adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produit", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Produit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.Fournisseur FournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.Vente[] VenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_expirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.Fournisseur Fournisseur {
            get {
                return this.FournisseurField;
            }
            set {
                if ((object.ReferenceEquals(this.FournisseurField, value) != true)) {
                    this.FournisseurField = value;
                    this.RaisePropertyChanged("Fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.Vente[] Vente {
            get {
                return this.VenteField;
            }
            set {
                if ((object.ReferenceEquals(this.VenteField, value) != true)) {
                    this.VenteField = value;
                    this.RaisePropertyChanged("Vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_expiration {
            get {
                return this.date_expirationField;
            }
            set {
                if ((this.date_expirationField.Equals(value) != true)) {
                    this.date_expirationField = value;
                    this.RaisePropertyChanged("date_expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_vente {
            get {
                return this.prix_venteField;
            }
            set {
                if ((this.prix_venteField.Equals(value) != true)) {
                    this.prix_venteField = value;
                    this.RaisePropertyChanged("prix_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LigneCommande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class LigneCommande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.Commande CommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ligneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_grossisteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.Commande Commande {
            get {
                return this.CommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandeField, value) != true)) {
                    this.CommandeField = value;
                    this.RaisePropertyChanged("Commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_ligneCommande {
            get {
                return this.id_ligneCommandeField;
            }
            set {
                if ((this.id_ligneCommandeField.Equals(value) != true)) {
                    this.id_ligneCommandeField = value;
                    this.RaisePropertyChanged("id_ligneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_grossiste {
            get {
                return this.prix_grossisteField;
            }
            set {
                if ((this.prix_grossisteField.Equals(value) != true)) {
                    this.prix_grossisteField = value;
                    this.RaisePropertyChanged("prix_grossiste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vente", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Vente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantite_venduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_vente {
            get {
                return this.id_venteField;
            }
            set {
                if ((this.id_venteField.Equals(value) != true)) {
                    this.id_venteField = value;
                    this.RaisePropertyChanged("id_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite_vendu {
            get {
                return this.quantite_venduField;
            }
            set {
                if ((this.quantite_venduField.Equals(value) != true)) {
                    this.quantite_venduField = value;
                    this.RaisePropertyChanged("quantite_vendu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Commande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.FournisseurService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> confirmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_arriveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_souhaiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_commandeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.FournisseurService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> confirme {
            get {
                return this.confirmeField;
            }
            set {
                if ((this.confirmeField.Equals(value) != true)) {
                    this.confirmeField = value;
                    this.RaisePropertyChanged("confirme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_arrive {
            get {
                return this.date_arriveField;
            }
            set {
                if ((this.date_arriveField.Equals(value) != true)) {
                    this.date_arriveField = value;
                    this.RaisePropertyChanged("date_arrive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_commande {
            get {
                return this.date_commandeField;
            }
            set {
                if ((this.date_commandeField.Equals(value) != true)) {
                    this.date_commandeField = value;
                    this.RaisePropertyChanged("date_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_souhaite {
            get {
                return this.date_souhaiteField;
            }
            set {
                if ((this.date_souhaiteField.Equals(value) != true)) {
                    this.date_souhaiteField = value;
                    this.RaisePropertyChanged("date_souhaite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FournisseurService.IFournisseurServiceWCF")]
    public interface IFournisseurServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/add", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/addResponse")]
        void add(GestionDeStockI3M.FournisseurService.Fournisseur f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/add", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/addResponse")]
        System.Threading.Tasks.Task addAsync(GestionDeStockI3M.FournisseurService.Fournisseur f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findAll", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findAllResponse")]
        GestionDeStockI3M.FournisseurService.Fournisseur[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findAll", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findAllResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/find", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findResponse")]
        GestionDeStockI3M.FournisseurService.Fournisseur find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/find", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur> findAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findName", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findNameResponse")]
        string findName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findName", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findNameResponse")]
        System.Threading.Tasks.Task<string> findNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/delete", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/deleteResponse")]
        void delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/delete", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/modifier", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/modifierResponse")]
        void modifier(GestionDeStockI3M.FournisseurService.Fournisseur f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/modifier", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/modifierResponse")]
        System.Threading.Tasks.Task modifierAsync(GestionDeStockI3M.FournisseurService.Fournisseur f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findNom", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findNomResponse")]
        GestionDeStockI3M.FournisseurService.Fournisseur[] findNom(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findNom", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findNomResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur[]> findNomAsync(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findbyId", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findbyIdResponse")]
        GestionDeStockI3M.FournisseurService.Fournisseur[] findbyId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFournisseurServiceWCF/findbyId", ReplyAction="http://tempuri.org/IFournisseurServiceWCF/findbyIdResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur[]> findbyIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFournisseurServiceWCFChannel : GestionDeStockI3M.FournisseurService.IFournisseurServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FournisseurServiceWCFClient : System.ServiceModel.ClientBase<GestionDeStockI3M.FournisseurService.IFournisseurServiceWCF>, GestionDeStockI3M.FournisseurService.IFournisseurServiceWCF {
        
        public FournisseurServiceWCFClient() {
        }
        
        public FournisseurServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FournisseurServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FournisseurServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FournisseurServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void add(GestionDeStockI3M.FournisseurService.Fournisseur f) {
            base.Channel.add(f);
        }
        
        public System.Threading.Tasks.Task addAsync(GestionDeStockI3M.FournisseurService.Fournisseur f) {
            return base.Channel.addAsync(f);
        }
        
        public GestionDeStockI3M.FournisseurService.Fournisseur[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public GestionDeStockI3M.FournisseurService.Fournisseur find(int id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur> findAsync(int id) {
            return base.Channel.findAsync(id);
        }
        
        public string findName(int id) {
            return base.Channel.findName(id);
        }
        
        public System.Threading.Tasks.Task<string> findNameAsync(int id) {
            return base.Channel.findNameAsync(id);
        }
        
        public void delete(int id) {
            base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        public void modifier(GestionDeStockI3M.FournisseurService.Fournisseur f) {
            base.Channel.modifier(f);
        }
        
        public System.Threading.Tasks.Task modifierAsync(GestionDeStockI3M.FournisseurService.Fournisseur f) {
            return base.Channel.modifierAsync(f);
        }
        
        public GestionDeStockI3M.FournisseurService.Fournisseur[] findNom(string n) {
            return base.Channel.findNom(n);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur[]> findNomAsync(string n) {
            return base.Channel.findNomAsync(n);
        }
        
        public GestionDeStockI3M.FournisseurService.Fournisseur[] findbyId(int id) {
            return base.Channel.findbyId(id);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.FournisseurService.Fournisseur[]> findbyIdAsync(int id) {
            return base.Channel.findbyIdAsync(id);
        }
    }
}
