//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3M.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passewordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passeword {
            get {
                return this.passewordField;
            }
            set {
                if ((object.ReferenceEquals(this.passewordField, value) != true)) {
                    this.passewordField = value;
                    this.RaisePropertyChanged("passeword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserServiceWCF")]
    public interface IUserServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceWCF/add", ReplyAction="http://tempuri.org/IUserServiceWCF/addResponse")]
        void add(GestionDeStockI3M.UserService.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceWCF/add", ReplyAction="http://tempuri.org/IUserServiceWCF/addResponse")]
        System.Threading.Tasks.Task addAsync(GestionDeStockI3M.UserService.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceWCF/getAll", ReplyAction="http://tempuri.org/IUserServiceWCF/getAllResponse")]
        GestionDeStockI3M.UserService.User[] getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServiceWCF/getAll", ReplyAction="http://tempuri.org/IUserServiceWCF/getAllResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.UserService.User[]> getAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceWCFChannel : GestionDeStockI3M.UserService.IUserServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceWCFClient : System.ServiceModel.ClientBase<GestionDeStockI3M.UserService.IUserServiceWCF>, GestionDeStockI3M.UserService.IUserServiceWCF {
        
        public UserServiceWCFClient() {
        }
        
        public UserServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void add(GestionDeStockI3M.UserService.User u) {
            base.Channel.add(u);
        }
        
        public System.Threading.Tasks.Task addAsync(GestionDeStockI3M.UserService.User u) {
            return base.Channel.addAsync(u);
        }
        
        public GestionDeStockI3M.UserService.User[] getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.UserService.User[]> getAllAsync() {
            return base.Channel.getAllAsync();
        }
    }
}
