//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStockI3M.DashboardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vente", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Vente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantite_venduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_vente {
            get {
                return this.id_venteField;
            }
            set {
                if ((this.id_venteField.Equals(value) != true)) {
                    this.id_venteField = value;
                    this.RaisePropertyChanged("id_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite_vendu {
            get {
                return this.quantite_venduField;
            }
            set {
                if ((this.quantite_venduField.Equals(value) != true)) {
                    this.quantite_venduField = value;
                    this.RaisePropertyChanged("quantite_vendu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produit", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Produit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.Fournisseur FournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.Vente[] VenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_ajoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_expirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_venteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.Fournisseur Fournisseur {
            get {
                return this.FournisseurField;
            }
            set {
                if ((object.ReferenceEquals(this.FournisseurField, value) != true)) {
                    this.FournisseurField = value;
                    this.RaisePropertyChanged("Fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.Vente[] Vente {
            get {
                return this.VenteField;
            }
            set {
                if ((object.ReferenceEquals(this.VenteField, value) != true)) {
                    this.VenteField = value;
                    this.RaisePropertyChanged("Vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_ajout {
            get {
                return this.date_ajoutField;
            }
            set {
                if ((this.date_ajoutField.Equals(value) != true)) {
                    this.date_ajoutField = value;
                    this.RaisePropertyChanged("date_ajout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_expiration {
            get {
                return this.date_expirationField;
            }
            set {
                if ((this.date_expirationField.Equals(value) != true)) {
                    this.date_expirationField = value;
                    this.RaisePropertyChanged("date_expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_vente {
            get {
                return this.prix_venteField;
            }
            set {
                if ((this.prix_venteField.Equals(value) != true)) {
                    this.prix_venteField = value;
                    this.RaisePropertyChanged("prix_vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fournisseur", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Fournisseur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.Produit[] ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.Produit[] Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseField, value) != true)) {
                    this.adresseField = value;
                    this.RaisePropertyChanged("adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_fournisseur {
            get {
                return this.id_fournisseurField;
            }
            set {
                if ((this.id_fournisseurField.Equals(value) != true)) {
                    this.id_fournisseurField = value;
                    this.RaisePropertyChanged("id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LigneCommande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class LigneCommande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.Commande CommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.Produit ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ligneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_grossisteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.Commande Commande {
            get {
                return this.CommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandeField, value) != true)) {
                    this.CommandeField = value;
                    this.RaisePropertyChanged("Commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.Produit Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_ligneCommande {
            get {
                return this.id_ligneCommandeField;
            }
            set {
                if ((this.id_ligneCommandeField.Equals(value) != true)) {
                    this.id_ligneCommandeField = value;
                    this.RaisePropertyChanged("id_ligneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_grossiste {
            get {
                return this.prix_grossisteField;
            }
            set {
                if ((this.prix_grossisteField.Equals(value) != true)) {
                    this.prix_grossisteField = value;
                    this.RaisePropertyChanged("prix_grossiste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commande", Namespace="http://schemas.datacontract.org/2004/07/GestionDeStockI3MServiceWCF")]
    [System.SerializableAttribute()]
    public partial class Commande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionDeStockI3M.DashboardService.LigneCommande[] LigneCommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> confirmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_arriveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_souhaiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_commandeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionDeStockI3M.DashboardService.LigneCommande[] LigneCommande {
            get {
                return this.LigneCommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneCommandeField, value) != true)) {
                    this.LigneCommandeField = value;
                    this.RaisePropertyChanged("LigneCommande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> confirme {
            get {
                return this.confirmeField;
            }
            set {
                if ((this.confirmeField.Equals(value) != true)) {
                    this.confirmeField = value;
                    this.RaisePropertyChanged("confirme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_arrive {
            get {
                return this.date_arriveField;
            }
            set {
                if ((this.date_arriveField.Equals(value) != true)) {
                    this.date_arriveField = value;
                    this.RaisePropertyChanged("date_arrive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_commande {
            get {
                return this.date_commandeField;
            }
            set {
                if ((this.date_commandeField.Equals(value) != true)) {
                    this.date_commandeField = value;
                    this.RaisePropertyChanged("date_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_souhaite {
            get {
                return this.date_souhaiteField;
            }
            set {
                if ((this.date_souhaiteField.Equals(value) != true)) {
                    this.date_souhaiteField = value;
                    this.RaisePropertyChanged("date_souhaite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DashboardService.IDashboardServiceWCF")]
    public interface IDashboardServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_ventes_total", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_ventes_totalResponse")]
        int nb_ventes_total();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_ventes_total", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_ventes_totalResponse")]
        System.Threading.Tasks.Task<int> nb_ventes_totalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_ventes", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_ventesResponse")]
        int nb_ventes(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_ventes", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_ventesResponse")]
        System.Threading.Tasks.Task<int> nb_ventesAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gainResponse")]
        int gain(int id, System.DateTime d, int id_vente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gainResponse")]
        System.Threading.Tasks.Task<int> gainAsync(int id, System.DateTime d, int id_vente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain1", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain1Response")]
        int gain1(int id, int m, int id_vente, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain1", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain1Response")]
        System.Threading.Tasks.Task<int> gain1Async(int id, int m, int id_vente, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/prix_prod", ReplyAction="http://tempuri.org/IDashboardServiceWCF/prix_prodResponse")]
        int prix_prod(int id, int quantite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/prix_prod", ReplyAction="http://tempuri.org/IDashboardServiceWCF/prix_prodResponse")]
        System.Threading.Tasks.Task<int> prix_prodAsync(int id, int quantite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain_tout", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain_toutResponse")]
        int gain_tout(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain_tout", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain_toutResponse")]
        System.Threading.Tasks.Task<int> gain_toutAsync(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/perte", ReplyAction="http://tempuri.org/IDashboardServiceWCF/perteResponse")]
        int perte(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/perte", ReplyAction="http://tempuri.org/IDashboardServiceWCF/perteResponse")]
        System.Threading.Tasks.Task<int> perteAsync(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findAll", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findAllResponse")]
        GestionDeStockI3M.DashboardService.Vente[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findAll", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findAllResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findByMounth", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findByMounthResponse")]
        GestionDeStockI3M.DashboardService.Vente[] findByMounth(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findByMounth", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findByMounthResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findByMounthAsync(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findByYear", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findByYearResponse")]
        GestionDeStockI3M.DashboardService.Vente[] findByYear(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findByYear", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findByYearResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findByYearAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findByDay", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findByDayResponse")]
        GestionDeStockI3M.DashboardService.Vente[] findByDay(int d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findByDay", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findByDayResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findByDayAsync(int d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findnow", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findnowResponse")]
        GestionDeStockI3M.DashboardService.Vente[] findnow(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/findnow", ReplyAction="http://tempuri.org/IDashboardServiceWCF/findnowResponse")]
        System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findnowAsync(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/QuantiteMonth", ReplyAction="http://tempuri.org/IDashboardServiceWCF/QuantiteMonthResponse")]
        int QuantiteMonth(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/QuantiteMonth", ReplyAction="http://tempuri.org/IDashboardServiceWCF/QuantiteMonthResponse")]
        System.Threading.Tasks.Task<int> QuantiteMonthAsync(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_venteByMonth", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_venteByMonthResponse")]
        int nb_venteByMonth(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_venteByMonth", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_venteByMonthResponse")]
        System.Threading.Tasks.Task<int> nb_venteByMonthAsync(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain_month", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain_monthResponse")]
        int gain_month(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain_month", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain_monthResponse")]
        System.Threading.Tasks.Task<int> gain_monthAsync(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_produit_des", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_produit_desResponse")]
        int nb_produit_des(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_produit_des", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_produit_desResponse")]
        System.Threading.Tasks.Task<int> nb_produit_desAsync(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/qu", ReplyAction="http://tempuri.org/IDashboardServiceWCF/quResponse")]
        int qu(int id, System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/qu", ReplyAction="http://tempuri.org/IDashboardServiceWCF/quResponse")]
        System.Threading.Tasks.Task<int> quAsync(int id, System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/QuantiteYear", ReplyAction="http://tempuri.org/IDashboardServiceWCF/QuantiteYearResponse")]
        int QuantiteYear(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/QuantiteYear", ReplyAction="http://tempuri.org/IDashboardServiceWCF/QuantiteYearResponse")]
        System.Threading.Tasks.Task<int> QuantiteYearAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_venteByYear", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_venteByYearResponse")]
        int nb_venteByYear(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nb_venteByYear", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nb_venteByYearResponse")]
        System.Threading.Tasks.Task<int> nb_venteByYearAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain_year", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain_yearResponse")]
        decimal gain_year(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/gain_year", ReplyAction="http://tempuri.org/IDashboardServiceWCF/gain_yearResponse")]
        System.Threading.Tasks.Task<decimal> gain_yearAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/perte_year", ReplyAction="http://tempuri.org/IDashboardServiceWCF/perte_yearResponse")]
        decimal perte_year(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/perte_year", ReplyAction="http://tempuri.org/IDashboardServiceWCF/perte_yearResponse")]
        System.Threading.Tasks.Task<decimal> perte_yearAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/QuantityWeek", ReplyAction="http://tempuri.org/IDashboardServiceWCF/QuantityWeekResponse")]
        int QuantityWeek(System.DateTime d, System.DateTime dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/QuantityWeek", ReplyAction="http://tempuri.org/IDashboardServiceWCF/QuantityWeekResponse")]
        System.Threading.Tasks.Task<int> QuantityWeekAsync(System.DateTime d, System.DateTime dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/name_prod", ReplyAction="http://tempuri.org/IDashboardServiceWCF/name_prodResponse")]
        string name_prod(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/name_prod", ReplyAction="http://tempuri.org/IDashboardServiceWCF/name_prodResponse")]
        System.Threading.Tasks.Task<string> name_prodAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nbr_achat", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nbr_achatResponse")]
        int nbr_achat(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/nbr_achat", ReplyAction="http://tempuri.org/IDashboardServiceWCF/nbr_achatResponse")]
        System.Threading.Tasks.Task<int> nbr_achatAsync(System.DateTime d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/q_v_m", ReplyAction="http://tempuri.org/IDashboardServiceWCF/q_v_mResponse")]
        int q_v_m(int id, int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/q_v_m", ReplyAction="http://tempuri.org/IDashboardServiceWCF/q_v_mResponse")]
        System.Threading.Tasks.Task<int> q_v_mAsync(int id, int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/perte_mois", ReplyAction="http://tempuri.org/IDashboardServiceWCF/perte_moisResponse")]
        int perte_mois(int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardServiceWCF/perte_mois", ReplyAction="http://tempuri.org/IDashboardServiceWCF/perte_moisResponse")]
        System.Threading.Tasks.Task<int> perte_moisAsync(int m, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDashboardServiceWCFChannel : GestionDeStockI3M.DashboardService.IDashboardServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashboardServiceWCFClient : System.ServiceModel.ClientBase<GestionDeStockI3M.DashboardService.IDashboardServiceWCF>, GestionDeStockI3M.DashboardService.IDashboardServiceWCF {
        
        public DashboardServiceWCFClient() {
        }
        
        public DashboardServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashboardServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int nb_ventes_total() {
            return base.Channel.nb_ventes_total();
        }
        
        public System.Threading.Tasks.Task<int> nb_ventes_totalAsync() {
            return base.Channel.nb_ventes_totalAsync();
        }
        
        public int nb_ventes(System.DateTime date) {
            return base.Channel.nb_ventes(date);
        }
        
        public System.Threading.Tasks.Task<int> nb_ventesAsync(System.DateTime date) {
            return base.Channel.nb_ventesAsync(date);
        }
        
        public int gain(int id, System.DateTime d, int id_vente) {
            return base.Channel.gain(id, d, id_vente);
        }
        
        public System.Threading.Tasks.Task<int> gainAsync(int id, System.DateTime d, int id_vente) {
            return base.Channel.gainAsync(id, d, id_vente);
        }
        
        public int gain1(int id, int m, int id_vente, int y) {
            return base.Channel.gain1(id, m, id_vente, y);
        }
        
        public System.Threading.Tasks.Task<int> gain1Async(int id, int m, int id_vente, int y) {
            return base.Channel.gain1Async(id, m, id_vente, y);
        }
        
        public int prix_prod(int id, int quantite) {
            return base.Channel.prix_prod(id, quantite);
        }
        
        public System.Threading.Tasks.Task<int> prix_prodAsync(int id, int quantite) {
            return base.Channel.prix_prodAsync(id, quantite);
        }
        
        public int gain_tout(System.DateTime d) {
            return base.Channel.gain_tout(d);
        }
        
        public System.Threading.Tasks.Task<int> gain_toutAsync(System.DateTime d) {
            return base.Channel.gain_toutAsync(d);
        }
        
        public int perte(System.DateTime d) {
            return base.Channel.perte(d);
        }
        
        public System.Threading.Tasks.Task<int> perteAsync(System.DateTime d) {
            return base.Channel.perteAsync(d);
        }
        
        public GestionDeStockI3M.DashboardService.Vente[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public GestionDeStockI3M.DashboardService.Vente[] findByMounth(int m, int y) {
            return base.Channel.findByMounth(m, y);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findByMounthAsync(int m, int y) {
            return base.Channel.findByMounthAsync(m, y);
        }
        
        public GestionDeStockI3M.DashboardService.Vente[] findByYear(int y) {
            return base.Channel.findByYear(y);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findByYearAsync(int y) {
            return base.Channel.findByYearAsync(y);
        }
        
        public GestionDeStockI3M.DashboardService.Vente[] findByDay(int d) {
            return base.Channel.findByDay(d);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findByDayAsync(int d) {
            return base.Channel.findByDayAsync(d);
        }
        
        public GestionDeStockI3M.DashboardService.Vente[] findnow(System.DateTime d) {
            return base.Channel.findnow(d);
        }
        
        public System.Threading.Tasks.Task<GestionDeStockI3M.DashboardService.Vente[]> findnowAsync(System.DateTime d) {
            return base.Channel.findnowAsync(d);
        }
        
        public int QuantiteMonth(int m, int y) {
            return base.Channel.QuantiteMonth(m, y);
        }
        
        public System.Threading.Tasks.Task<int> QuantiteMonthAsync(int m, int y) {
            return base.Channel.QuantiteMonthAsync(m, y);
        }
        
        public int nb_venteByMonth(int m, int y) {
            return base.Channel.nb_venteByMonth(m, y);
        }
        
        public System.Threading.Tasks.Task<int> nb_venteByMonthAsync(int m, int y) {
            return base.Channel.nb_venteByMonthAsync(m, y);
        }
        
        public int gain_month(int m, int y) {
            return base.Channel.gain_month(m, y);
        }
        
        public System.Threading.Tasks.Task<int> gain_monthAsync(int m, int y) {
            return base.Channel.gain_monthAsync(m, y);
        }
        
        public int nb_produit_des(System.DateTime d) {
            return base.Channel.nb_produit_des(d);
        }
        
        public System.Threading.Tasks.Task<int> nb_produit_desAsync(System.DateTime d) {
            return base.Channel.nb_produit_desAsync(d);
        }
        
        public int qu(int id, System.DateTime d) {
            return base.Channel.qu(id, d);
        }
        
        public System.Threading.Tasks.Task<int> quAsync(int id, System.DateTime d) {
            return base.Channel.quAsync(id, d);
        }
        
        public int QuantiteYear(int y) {
            return base.Channel.QuantiteYear(y);
        }
        
        public System.Threading.Tasks.Task<int> QuantiteYearAsync(int y) {
            return base.Channel.QuantiteYearAsync(y);
        }
        
        public int nb_venteByYear(int y) {
            return base.Channel.nb_venteByYear(y);
        }
        
        public System.Threading.Tasks.Task<int> nb_venteByYearAsync(int y) {
            return base.Channel.nb_venteByYearAsync(y);
        }
        
        public decimal gain_year(int y) {
            return base.Channel.gain_year(y);
        }
        
        public System.Threading.Tasks.Task<decimal> gain_yearAsync(int y) {
            return base.Channel.gain_yearAsync(y);
        }
        
        public decimal perte_year(int y) {
            return base.Channel.perte_year(y);
        }
        
        public System.Threading.Tasks.Task<decimal> perte_yearAsync(int y) {
            return base.Channel.perte_yearAsync(y);
        }
        
        public int QuantityWeek(System.DateTime d, System.DateTime dd) {
            return base.Channel.QuantityWeek(d, dd);
        }
        
        public System.Threading.Tasks.Task<int> QuantityWeekAsync(System.DateTime d, System.DateTime dd) {
            return base.Channel.QuantityWeekAsync(d, dd);
        }
        
        public string name_prod(int i) {
            return base.Channel.name_prod(i);
        }
        
        public System.Threading.Tasks.Task<string> name_prodAsync(int i) {
            return base.Channel.name_prodAsync(i);
        }
        
        public int nbr_achat(System.DateTime d) {
            return base.Channel.nbr_achat(d);
        }
        
        public System.Threading.Tasks.Task<int> nbr_achatAsync(System.DateTime d) {
            return base.Channel.nbr_achatAsync(d);
        }
        
        public int q_v_m(int id, int m, int y) {
            return base.Channel.q_v_m(id, m, y);
        }
        
        public System.Threading.Tasks.Task<int> q_v_mAsync(int id, int m, int y) {
            return base.Channel.q_v_mAsync(id, m, y);
        }
        
        public int perte_mois(int m, int y) {
            return base.Channel.perte_mois(m, y);
        }
        
        public System.Threading.Tasks.Task<int> perte_moisAsync(int m, int y) {
            return base.Channel.perte_moisAsync(m, y);
        }
    }
}
